services:
  db:
    image: timescale/timescaledb:latest-pg15
    container_name: elpis_postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      # Persist data to a host folder for easy backups & inspection:
      - ./data/db:/var/lib/postgresql/data
      # Init scripts (run only once when ./data/db is empty)
      - ./db/init:/docker-entrypoint-initdb.d:ro

# No named volumes here—./data/db is in your project folder.
