name: docs

# Needed scopes for the Pages actions
permissions:
  contents: read          # checkout
  pages: write            # upload & deploy
  id-token: write         # auth to Pages

on:
  push:
    paths: [ "elpis_documentation/**" ]
  workflow_dispatch:

concurrency:
  group: docs-build
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1) Checkout
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 2) Setup Python
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    # 3) Build the Jupyter-Book
    - name: Build book
      run: |
        pip install -q jupyter-book
        cd elpis_documentation
        jupyter-book build . --all

    # 4) Upload the generated HTML as a Pages artifact
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: elpis_documentation/_build/html

    # 5) Deploy to GitHub Pages
    - name: Deploy to Pages
      id: deployment
      uses: actions/deploy-pages@v4
