name: Build & Deploy Documentation

# Grant push rights to GITHUB_TOKEN
permissions:
  contents: write

on:
  push:
    paths:
      - "elpis_documentation/**"
  workflow_dispatch:

concurrency:
  group: docs-build
  cancel-in-progress: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter-book

      - name: Build the Jupyter Book
        run: |
          cd elpis_documentation
          jupyter-book build . --all

      - name: Publish to gh-pages
        run: |
          cd elpis_documentation/_build/html
          git init -b gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Publish docs: $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          git push --force \
            "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" \
            gh-pages
