name: Build & Deploy Documentation

on:
  push:
    paths:
      - "elpis_documentation/**"
  workflow_dispatch:

# Concurrency prevents multiple queued runs from piling up
concurrency:
  group: docs-build
  cancel-in-progress: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter-book ghp-import

      - name: Build the Jupyter Book
        run: |
          cd elpis_documentation
          jupyter-book build . --all

      - name: Publish to GitHub Pages
        run: |
          cd elpis_documentation/_build/html
          git init -b gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Publish docs: $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          # Push to gh-pages branch via the token-authenticated URL
          git push --force \
            "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" \
            gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
