name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1) Install Miniconda and create your env from YAML
      - name: Set up Conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          # If you need a specific Python version, set python-version here
          # python-version: "3.11"
          environment-file: environment_setup.yml
          activate-environment: elpis

      # 2) (Re-)install test tools in that env
      - name: Install test & lint dependencies
        shell: bash -l {0}
        run: |
          conda install --yes pytest pytest-cov flake8 click tabulate beautifulsoup4
          # if you have other test deps not in your yml, add them here

      # 3) Lint
      - name: Lint with flake8
        shell: bash -l {0}
        run: |
          flake8 src/elpis_nautilus tests

      # 4) Run pytest with coverage
      - name: Run tests with coverage
        shell: bash -l {0}
        run: |
          pytest --cov=src/elpis_nautilus --cov-report=xml

      # 5) Upload to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
          fail_ci_if_error: true
