name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1) Install Miniconda and create your env from YAML
      - name: Set up Conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment_setup.yml
          activate-environment: elpis

      # 1.1) Install your package
      - name: Install your package
        shell: bash -l {0}
        run: |
          pip install -e .

      # 2) (Re-)install test tools in that env
      - name: Install test & lint dependencies
        shell: bash -l {0}
        run: |
          conda install --yes pytest pytest-cov flake8 click tabulate beautifulsoup4 pylint

      # 3) Lint with Pylint (badge update & score check)
      - name: Lint with Pylint
        uses: Silleellie/pylint-github-action@v2.1
        with:
          lint-path: |
            src/elpis_nautilus
          python-version: 3.9
          readme-path: README.md
          pylintrc-path: .pylintrc
          # disable the default requirements.txt install
          requirements-path: ""
          badge-text: PyLint
          color-bad-score: red
          color-ok-score: orange
          color-good-score: yellow
          color-perfect-score: brightgreen

      # 4) Lint with flake8
      - name: Lint with flake8
        shell: bash -l {0}
        run: |
          flake8 src/elpis_nautilus tests

      # 5) Run pytest with coverage
      - name: Run tests with coverage
        shell: bash -l {0}
        run: |
          pytest --cov=src/elpis_nautilus --cov-branch --cov-report=xml

      # 6) Upload to Codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          fail_ci_if_error: true
